OUTPUT_ARCH(i386)
ENTRY(start)
SECTIONS
{
	offset = 0xC0000000;
	. = 0xC0100000;
	kernel_start = .;
	.text ALIGN(4K) : AT (ADDR(.text) - offset)
	{
		*(.start)
		*(.text)
	}
	.rodata ALIGN(4K) : AT (ADDR(.rodata) - offset)
	{
		*(.rodata.*)
		*(.eh_frame)
	}
	.data ALIGN(4K) : AT (ADDR(.data) - offset)
	{
		*(.data)
	}
	.bss ALIGN(4K) : AT (ADDR(.bss) - offset)
	{
		*(COMMON)
		*(.bss)
	}
	kernel_end = .;
}
