OUTPUT_ARCH(i386)
ENTRY(start)
SECTIONS
{
	. = 0xE0100000;
	kernel_start = .;
	.text ALIGN(4K) : AT (ADDR(.text) - 0xE0000000)
	{
		*(.start)
		*(.text)
	}
	.rodata ALIGN(4K) : AT (ADDR(.rodata) - 0xE0000000)
	{
		*(.rodata.*)
		*(.eh_frame)
	}
	.data ALIGN(4K) : AT (ADDR(.data) - 0xE0000000)
	{
		*(.data)
	}
	.bss ALIGN(4K) : AT (ADDR(.bss) - 0xE0000000)
	{
		*(COMMON)
		*(.bss)
	}
	kernel_end = .;
}
